# MongoDB url
database: mongodb://localhost/thoth

# Web server configuration
server:
  # Basic Auth Realm
  realm: Thoth
  # IP Address the server will listening to (0.0.0.0 to listen all)
  host: 127.0.0.1
  # Server port
  port: 8080
  # Should we serve the Web client app ?
  serveClient: True
  # Use HTTPS ? (if key & cert specified, automatically use HTTPS)
  ssl:
    key: # Path to key
    cert: # Path to certificate
    pfx: # 

encryption:
  # Encryption algorithm to use
  algorithm: aes256
  # Path to store the passphrase verification HMAC
  hmacPath: .hmac # Pass to the hmac used to detect passphrase change

log:
  level: info
  colorize: False # Use ANSI colors in logs
  timestamp: True # Timestamp log outputs

rbac:
  admin: # can do everything on everything
    - action: '*'
      subject: '*'

export:
  template: |
    <%- label %>
    ============

    <%- text %>

    Meta
    ----
    
    - **Category**: <%- category %>
    - **Creator:** <%- creator.email %>
    - **Creation Date:** <%- creationDate %>
    - **Last update:** <%- lastUpdate %>
    - **Revision:** <%- revision %>