server:
  host: 0.0.0.0
  port: 4443
  ssl:
    key: ./ssl-test/server.key
    cert: ./ssl-test/server.crt

auth: ldap

log:
  colorize: True
  level: debug

plugins:
  thoth-ldap-auth:
    path: ./plugins/thoth-ldap-auth
    options:
      dn: ou=personnels EN,ou=ac-dijon,ou=education,o=gouv,c=fr
      scope: sub
      url: ldap://ldap-m2.in.ac-dijon.fr
      port: 389
      filter: uid=${username}
      validator: ^[A-Za-z-_0-9]+$
      cacheTimeout: 60000
      nameField: cn
      emailField: mail

rbac:

  dev-local:

    - action: CREATE
      subject: Application.Local
    - action: READ
      subject: Application.Local
    - action: UPDATE
      subject: Application.Local
    - action: DELETE
      subject: Application.Local

  dev-nat:

    - action: CREATE
      subject: Application.Nat
    - action: READ
      subject: Application.Nat
    - action: UPDATE
      subject: Application.Nat
    - action: DELETE
      subject: Application.Nat

  sysadmin-web:

    - action: READ
      subject: Machine.Web
    - action: UPDATE
      subject: Machine.Web
    - action: CREATE
      subject: Machine.Web
    - action: DELETE
      subject: Machine.Web

  sysadmin-nat:

    - action: READ
      subject: Machine.Nat
    - action: UPDATE
      subject: Machine.Nat
    - action: CREATE
      subject: Machine.Nat
    - action: DELETE
      subject: Machine.Nat

  webmaster:

    - action: READ
      subject: Site
    - action: CREATE
      subject: Site
    - action: DELETE
      subject: Site
    - action: UPDATE
      subject: Site